version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run: echo "test"
    # EC2 に SSH 接続・デプロイを実行
    deploy:
        docker:
            image: circleci/node:8
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            - run:
                command: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/sampleNuxt && git pull'
            - run:
                command: pm2 kill
            - run:
                command: yarn install
            - run:
                command: yarn build
            - run:
                command: pm2 start npm --name sampleNuxt -- start
            - run:
                command: sudo service nginx restart
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    # build ジョブに依存してるので、先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy
                filters:
                    branches:
                        only: master