version: 2.0
jobs:
    build:
        docker:
            - image: circleci/node:11.1
        steps:
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    # EC2 に SSH 接続・デプロイを実行
    deploy:
        docker:
            - image: circleci/node:11.1
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/sampleNuxt && git pull'
            - run:
              name: pm2
              command: pm2 kill
            - run:
              name: yarn
              command: yarn install
            - run:
              name: yarn buil
              command: yarn build
            - run:
              name: pm2 start
              command: pm2 start npm --name sampleNuxt -- start
            - run:
              name: nginx
              command: sudo service nginx restart
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    # build ジョブに依存してるので、先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy
                filters:
                    branches:
                        only: master